spring.application.name=filesanalyzer
server.port=${SERVER_PORT:8082}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/filesanalyzer_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:blaq}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ochola@254}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info
